### ISSUE TITLE
Do not wrap fastify.inject() in a promise, as it has anative promise API

### ISSUE THREAD

**Issue by mcollina** [fastify/aws-lambda-fastify#44]
## 🚀 Feature Proposal

`fastify.inject()` can return a promise as per https://www.fastify.io/docs/latest/Testing/#testing-with-http-injection.
Refactoring this code to avoid a `new Promise()` would simplify the logic quite a bit.

While we are at it, I would remove the `console.log(err)` and possibly document how to turn on logging.

**Comment by adrai** [comment]
Cool, thank you very mich for this suggestion.
Missed the promise api completely.
Will look at it as soon I’m back home again. Currently afk...
Was there already a Promise API for the inject function in v2?
Regarding the console.error... our experience tells us this is very important in regardless of the logging level. Is there a special reason for you to remove it?

**Comment by mcollina** [comment]
I think the error should be logged via the normal logging mechanism. By using `console.log` we make that error unparseable by other tooling.

I think mixing promises and callbacks leads to problems, and the lesser I see it the better. I would use async/await in this case anyway.

**Comment by adrai** [comment]
console.log is the “normal” logging in lambda 🤷‍♂️ -> https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html
(CloudWatch)

the problem is, this proxy function needs to work for all lambda api usages...
So, promise (async/await) and callback.
-> https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html

**Comment by mcollina** [comment]
I don’t understand either point :(. Can you please expand?

**Comment by adrai** [comment]
> I think the error should be logged via the normal logging mechanism. By using console.log we make that error unparseable by other tooling.

each stdout/stderr output in lambda is "prefixed/modified" anyway, i.e. 

`timestamp	request-id	log level (console.log/warn/error/...)	log-message`
`019-06-07T19:11:20.562Z	c793869b-ee49-115b-a5b6-4fd21e8dedac	INFO	msg`

```javascript
exports.handler = async function(event, context) {
  console.log("ENVIRONMENT VARIABLES\n" + JSON.stringify(process.env, null, 2))
  console.info("EVENT\n" + JSON.stringify(event, null, 2))
  console.warn("Event not processed.")
  return context.logStreamName
}
```

```
START RequestId: c793869b-ee49-115b-a5b6-4fd21e8dedac Version: $LATEST
2019-06-07T19:11:20.562Z	c793869b-ee49-115b-a5b6-4fd21e8dedac	INFO	ENVIRONMENT VARIABLES
{
  "AWS_LAMBDA_FUNCTION_VERSION": "$LATEST",
  "AWS_LAMBDA_LOG_GROUP_NAME": "/aws/lambda/my-function",
  "AWS_LAMBDA_LOG_STREAM_NAME": "2019/06/07/[$LATEST]e6f4a0c4241adcd70c262d34c0bbc85c",
  "AWS_EXECUTION_ENV": "AWS_Lambda_nodejs12.x",
  "AWS_LAMBDA_FUNCTION_NAME": "my-function",
  "PATH": "/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin",
  "NODE_PATH": "/opt/nodejs/node10/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules",
  ...
}
2019-06-07T19:11:20.563Z	c793869b-ee49-115b-a5b6-4fd21e8dedac	INFO	EVENT
{
  "key": "value"
}
2019-06-07T19:11:20.564Z	c793869b-ee49-115b-a5b6-4fd21e8dedac	WARN	Event not processed.
END RequestId: c793869b-ee49-115b-a5b6-4fd21e8dedac
REPORT RequestId: c793869b-ee49-115b-a5b6-4fd21e8dedac	Duration: 128.83 ms	Billed Duration: 200 ms	Memory Size: 128 MB	Max Memory Used: 74 MB	Init Duration: 166.62 ms	XRAY TraceId: 1-5d9d007f-0a8c7fd02xmpl480aed55ef0	SegmentId: 3d752xmpl1bbe37e	Sampled: true
```

=> https://docs.aws.amazon.com/lambda/latest/dg/nodejs-logging.html

---

> I think mixing promises and callbacks leads to problems, and the lesser I see it the better. I would use async/await in this case anyway.

a lambda signature can look like this:
```javascript
const awsLambdaFastify = require('aws-lambda-fastify')
const app = require('./app') // the fastify app
const proxy = awsLambdaFastify(app)

exports.handler = proxy
// or
exports.handler = (event, context, callback) => proxy(event, context, callback)
// or
exports.handler = (event, context) => proxy(event, context)
// or
exports.handler = async (event, context) => proxy(event, context)
```
so someone could prefer/use callback style, and someone else promise/async-await style...
this is why I have to use [promise or callback handling](https://github.com/fastify/aws-lambda-fastify/blob/master/index.js#L80), because the user can use one or the other...

=> https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html

---

I'm sorry, it was a busy day today, I may have misunderstood what you actually are trying to propose...

Otherwise I would have the suggestion that you try a PR, sometimes reading code is easier than reading text ;-)

**Comment by mcollina** [comment]
> each stdout/stderr output in lambda is "prefixed/modified" anyway, i.e.

I think those are applied to `process.stdout`, so it will reach pino as well.

---

Ok for the promise! I didn't notice.

**Comment by mcollina** [comment]
(Or at least give me an option to not call `console.log` but use the internal logger).

**Comment by adrai** [comment]
The internal (fastify’s) logger is used anyway if configured... the console statement is additional.
But if the fastify logging is not enables, at least that console statement works...
Does this hurt?
If so I can introduce an option to explictly disable that line. But at tthe moment I don’t see a real hurting reason for it. 🤷‍♂️

**Comment by mcollina** [comment]
Closing, as much as that log is annoying, it’s likely not worth the discussion of removing it.

**Comment by adrai** [comment]
I don't like you to be annoyed by that log statement.
I have 2 suggestions:

- introduce a new option i.e. `enableLogging` (defaults to true) or similar
- or something like this: `if (app.log.constructor.name !== 'Pino') console.error()`

what do you think?

**Comment by mcollina** [comment]
Really, I'm good with leaving it as is :). I was browsing the code and it popped over as something as I would never do. It's not worth to add complexity for this.

**Comment by adrai** [comment]
Ok, thx.
